@csapi_HostAddress = http://localhost:5045

GET {{csapi_HostAddress}}/weatherforecast/
Accept: application/json

GET {{csapi_HostAddress}}/entry
Accept: application/json

GET {{csapi_HostAddress}}/entry/1
Accept: application/json

GET {{csapi_HostAddress}}/entry/3
Accept: application/json

###
